version: '3'
services:
  my-app:
  image: cassudockerimages.azurecr.io/sample/my-app:1.0
  ports:
  - 3000:3000
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
    #named volume (name mongo-data) : path on the container
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
# a list of all the volumes you have defined in your docker compose and wil be mounted in your containers      
volumes:
  mongo-data:
    # driver: Local-persist
